Removed a number of RPMs that lead to conflicts during yum updates.
Example:
"Error: Package: libdrm-devel-2.4.59-2.el6.x86_64 (/libdrm-devel-2.4.59-2.el6.x86_64)
            Requires: libdrm = 2.4.59-2.el6
            Installed: libdrm-2.4.65-2.el6.x86_64 (@base)
                libdrm = 2.4.65-2.el6
 Error: Package: libxcb-devel-1.9.1-3.el6.x86_64 (/libxcb-devel-1.9.1-3.el6.x86_64)
            Requires: libxcb = 1.9.1-3.el6
            Available: libxcb-1.11-2.el6.i686 (base)
                libxcb = 1.11-2.el6"

Former-commit-id: fe671bd14d38189395d662e3c18540b1a9fc0ff1
Former-commit-id: c033efcd968c51377f518f053ac1634427500153
Former-commit-id: c007587fda989edb429a63ba0b9939152f7ec6c4 [formerly c993c7ec44ccf58e957bd9ae425507140ed85bf0]
Former-commit-id: 30ec522af1726df8674e9290a0fb410aa5ed1d2a
Former-commit-id: b75cb07f942f35869a175e91ae2a875d5510ae82 [formerly 28b635c3c8696bf9b85f982a4033e429f7b0c3e5]
Former-commit-id: 6382d95bf0c0aefd088ca6598803a1c9a1a68272